### ISSUE TITLE
request：want to get DSOs that DSO depend on

### ISSUE THREAD

**Issue by hsx2117** [terminaldweller/delf#1]
Hi, bro, can add a feature that user can get DSOs list info that depend on input DSO file?

**Comment by terminaldweller** [comment]
sure, but it's going to take me a couple of days. I have an exam soon.

**Comment by terminaldweller** [comment]
feel free to reopen the issue if there is any need.

**Comment by hsx2117** [comment]
Thanks, let me have a try

发自我的iPhone
